version: '3.8'

services:
  api:
    container_name: backend-api
    image: 905418362357.dkr.ecr.ap-southeast-1.amazonaws.com/work-enties:latest
    ports:
      - 8080:8080
    volumes:
      - /app/backend/images:/app/images
      - /app/backend/weights:/root/.deepface/weights
    networks:
      - network-db
    restart: on-failure

  db:
    container_name: mongo-db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=faceverify
      - MONGO_INITDB_ROOT_PASSWORD=faceverify1234
    ports:
      - 27017:27017
    volumes:
      - /app/db:/data/db
    networks:
      - network-db
    restart: on-failure
    
networks:
  network-db:
    name: faceverify
    driver: bridge